sap.idn.token-url=https://idn.seppay.ir/connect/token
sap.api.base-url=https://cpcpos.seppay.ir
sap.client.basic-authorization=Basic cm9jbGllbnQ6c2VjcmV0
sap.ro.username=username
sap.ro.password=password
sap.terminal-id=terminal-id